- name: "Struggling Student"
  initial_knowledge_prompt: "[PDF_TEXT_PERCENT:10]"
  guess_probability: 0.6
  hint_request_probability: 0.9
  hint_request_timing: "after_feedback"
  give_feedback_probability: 0.9
  accept_proactive_hint_probability: 0.8 # Likely to accept help
  min_think_time_ms: 7000
  max_think_time_ms: 15000

- name: "Anxious Student"
  initial_knowledge_prompt: "[PDF_TEXT_PERCENT:40]"
  guess_probability: 0.3
  hint_request_probability: 0.6
  hint_request_timing: "before_answer"
  give_feedback_probability: 1.0
  accept_proactive_hint_probability: 0.95 # Very likely to accept help
  min_think_time_ms: 8000
  max_think_time_ms: 17000

- name: "Confident but Wrong"
  initial_knowledge_prompt: "[PDF_TEXT_PERCENT:1]"
  guess_probability: 0.95
  hint_request_probability: 0.1
  hint_request_timing: "after_feedback"
  give_feedback_probability: 0.8
  accept_proactive_hint_probability: 0.2  # Unlikely to accept help
  min_think_time_ms: 3000
  max_think_time_ms: 10500

- name: "knowledgeable Student"
  initial_knowledge_prompt: "[PDF_TEXT_PERCENT:100]"
  guess_probability: 0.8
  hint_request_probability: 0.9
  hint_request_timing: "after_feedback"
  give_feedback_probability: 0.5
  accept_proactive_hint_probability: 0.5
  min_think_time_ms: 5000
  max_think_time_ms: 11000

- name: "Expert Student"
  initial_knowledge_prompt: "[Expert]"
  guess_probability: 0.5
  hint_request_probability: 0.5
  hint_request_timing: "after_feedback"
  give_feedback_probability: 0.9
  accept_proactive_hint_probability: 0.85
  min_think_time_ms: 2000
  max_think_time_ms: 10500
